---
# tasks file for apache-galaxy
  - name: "apache installation"
    yum:
      name: "httpd"
      state: "present"
  - name: "apache service activation"
    service:
      name: "httpd"
      state: "started"
      enabled: yes
